# Generated by Django 4.0.4 on 2022-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='cipher',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='core',
            name='finalOutput',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='core',
            name='outputImage',
            field=models.ImageField(default='frontend/src/default.jpg', upload_to='downloads/'),
        ),
    ]
