# Generated by Django 4.0.4 on 2022-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0003_alter_core_outputimage_imageoutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoutputs',
            name='un',
            field=models.IntegerField(),
        ),
    ]
