# Generated by Django 4.0.4 on 2022-04-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0004_alter_imageoutputs_un'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoutputs',
            name='un',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageProcessingCore.core'),
        ),
    ]
