# Generated by Django 4.0.4 on 2022-04-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0005_alter_imageoutputs_un'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageoutputs',
            name='un',
        ),
        migrations.AddField(
            model_name='imageoutputs',
            name='un_id',
            field=models.IntegerField(default=0),
        ),
    ]
