# Generated by Django 4.0.4 on 2022-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0006_remove_imageoutputs_un_imageoutputs_un_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoutputs',
            name='cipher',
            field=models.TextField(default=''),
        ),
    ]
