# Generated by Django 4.0.4 on 2022-05-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0008_alter_imageoutputs_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('k', models.IntegerField()),
                ('outputImage', models.ImageField(default='frontend/src/default.jpg', upload_to='outputs/')),
                ('cipher', models.FileField(upload_to='')),
            ],
        ),
    ]
