# Generated by Django 4.0.4 on 2022-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0009_decryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='keys',
            field=models.TextField(default=''),
        ),
    ]
