# Generated by Django 4.0.4 on 2022-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0011_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryption',
            name='k',
        ),
        migrations.RemoveField(
            model_name='decryption',
            name='n',
        ),
        migrations.AddField(
            model_name='decryption',
            name='keys',
            field=models.FileField(default='file.txt', upload_to=''),
        ),
    ]
