# Generated by Django 4.0.4 on 2022-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0012_remove_decryption_k_remove_decryption_n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='sharesRGB',
            field=models.TextField(default=''),
        ),
    ]
