# Generated by Django 4.0.4 on 2022-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0013_core_sharesrgb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreId', models.IntegerField(default=0)),
                ('useremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
