# Generated by Django 4.0.4 on 2022-06-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0015_userimagelist_fromemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryption',
            name='cipher',
            field=models.FileField(default='file.txt', upload_to=''),
        ),
    ]
