# Generated by Django 4.0.4 on 2022-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0016_alter_decryption_cipher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagelist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
